---
# tasks file for roles/docker

- name: Install epel-release & yum-utils
  yum:
    name:
      - epel-release
      - yum-utils
    state: present
    update_cache: yes

- name: Install python-pip
  yum:
    name:
      - python-pip
    state: present
    update_cache: yes

- name: Upgrade pip
  pip:
    name:
      - pip
    state: present
    extra_args: --upgrade

- name: Install docker & docker-compose python libraries
  pip:
    name:
      - docker
      - docker-compose
    state: present
    extra_args: --upgrade

- name: Add docker repository
  command: >
    yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes

