version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: ferasmaali/webapp:latest
    ports:
      - 5000:5000
    volumes:
      - ./src:/code
    environment:
      WAIT_HOSTS: db:3306
      MYSQL_DATABASE: performance_api_app
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST: db
    restart: on-failure

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: ferasmaali/mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/run/mysql
    environment:
      MYSQL_DATABASE: performance_api_app
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD: mashi
      restart: on-failure

volumes:
  mysql_data:
