version: "3.8"

services:
  web:
    build: .
    image: ferasmaali/webapp:latest
    command: python3 app.py
    ports:
      - 5000:5000
    volumes:
      - ./src:/code
    restart: always

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/run/mysql
      - ${PWD}/volumes/mysqld:/var/run/mysqld
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: always

volumes:
  mysql_data:
