version: "3.8"

services:
  web:
    build: .
    image: ferasmaali/webapp:latest
    ports:
      - 5000:5000
    volumes:
      - ./src:/code
    environment:
      WAIT_HOSTS: db:3306
    restart: on-failure

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/run/mysql
      - ${PWD}/db_stuff/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: always

volumes:
  mysql_data:
