---

- hosts: all
  become: yes

  vars:
    repo_dir: /Internship-Performance-API

  vars_files:
    - github_credentials.yml
    - db_stuff/db_credentials.yml

  roles:
    - docker_installation

  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: Clone the repo
      git:
        repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/FerasMaali/Internship-Performance-API.git"
        dest: "{{ repo_dir }}"
        update: yes
        depth: 1
        version: improve_security

    # TODO: replace this with something else
    - name: docker-compose down
      docker_compose:
        project_src: "{{ repo_dir }}"
        state: absent

    - name: docker-compose up
      docker_compose:
        project_src: "{{ repo_dir }}"
        build: yes
        state: present
        recreate: always
      environment:
        MYSQL_USER: "{{ mysql_user }}"
        MYSQL_PASSWORD: "{{ mysql_password }}"

    - name: Create data-collecting cron jobs
      cron:
        name: data collector
        job: 
          export MYSQL_USER={{ mysql_user }};
          export MYSQL_PASSWORD={{ mysql_password }};
          {{ repo_dir }}/src/collect_data
