---

- hosts: all
  become: yes

  vars:
    repo_dir: /Internship-Performance-API

  vars_files:
    - github_credentials.yml

  # roles:
  #   - docker_installation

  tasks:
    # - name: Install git
    #   yum:
    #     name: git
    #     state: present

    # - name: Clone the repo
    #   git:
    #     repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/FerasMaali/Internship-Performance-API.git"
    #     dest: "{{ repo_dir }}"
    #     update: yes
    #     depth: 1

    # This identical to `compose down` (It deletes volumes)
    # TODO: replace this with something else
    - name: Delete previous version of the thing
      docker_compose:
        project_src: "{{ repo_dir }}"
        build: no
        state: absent

    - name: docker-compose up
      docker_compose:
        project_src: "{{ repo_dir }}"
        build: yes
        state: present
        recreate: always
