---

- hosts: localhost
  become: yes

  vars:
    repo_dir: /Internship-Performance-API

  vars_files:
    - github_credentials.yml

  roles:
    - docker_installation

  tasks:
    - name: Clone the repo
      git:
        repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/FerasMaali/Internship-Performance-API.git"
        dest: "{{ repo_dir }}"
        update: yes

    # This identical to `compose down` (It deletes volumes)
    # TODO: uncomment this
    - name: Preparing to start services
      docker_compose:
        project_src: "{{ repo_dir }}"
        build: no
        state: absent

    - name: Prepare to mount /var/run/mysqld directory
      file:
        path: "{{ repo_dir }}/volumes/mysqld"
        state: directory
        mode: '0777'

    - name: Start db service
      docker_compose:
        project_src: "{{ repo_dir }}"
        services:
          - db
        state: present

    # - name: Wait until mysql service is ready (mysqld.sock exists)
    #   wait_for:
    #     path: "{{ repo_dir }}/volumes/mysqld/mysqld.sock"

    - name: Start webapp
      docker_compose:
        project_src: "{{ repo_dir }}"
        build: yes
        services:
          - web
        state: present
