#!/usr/bin/env sh

# Move to base directory of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" >/dev/null 2>&1 && pwd  )"
cd $DIR

. ./collector_functions

cd ../..

echo "INSERT INTO \`cpu_usage\` \
	(\`usage\`) VALUES (`cpu_usage`);" \
	| docker-compose exec -T db mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" performance_api_app 2> /dev/null

echo "INSERT INTO \`mem_usage\` \
	(\`used\`, \`free\`) VALUES (`used_mem`, `free_mem`);" \
	| docker-compose exec -T db mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" performance_api_app 2> /dev/null

echo "INSERT INTO \`disk_usage\` \
	(\`used\`, \`free\`) VALUES (`used_disk`, `free_disk`);" \
	| docker-compose exec -T db mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" performance_api_app 2> /dev/null
