#!/usr/bin/env sh

cpu_usage() {
	top -bn2 -p1 | grep 'Cpu(s)' | tail -1 | awk -F'[:,]' '{ print $5 }' | awk '{ print 100 - $1}'
}

used_mem() {
	free -b | grep Mem | awk '{ print $3 }'
}

free_mem() {
	free -b | grep Mem | awk '{ print $7 }'
}

used_disk() {
	df -B1 | grep 'centos.*root' | awk '{ print $3 }'
}

free_disk() {
	df -B1 | grep 'centos.*root' | awk '{ print $4 }'
}

# Move to base directory of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" >/dev/null 2>&1 && pwd  )"
cd $DIR
cd ..

echo "INSERT INTO \`cpu_usage\` \
	(\`usage\`) VALUES (`cpu_usage`);" \
	| docker-compose exec -T db mysql -u "$MYSQL_USER" -p "$MYSQL_PASSWORD" performance_api_app 2> /dev/null

echo "INSERT INTO \`mem_usage\` \
	(\`used\`, \`free\`) VALUES (`used_mem`, `free_mem`);" \
	| docker-compose exec -T db mysql -u "$MYSQL_USER" -p "$MYSQL_PASSWORD" performance_api_app 2> /dev/null

echo "INSERT INTO \`disk_usage\` \
	(\`used\`, \`free\`) VALUES (`used_disk`, `free_disk`);" \
	| docker-compose exec -T db mysql -u "$MYSQL_USER" -p "$MYSQL_PASSWORD" performance_api_app 2> /dev/null
